export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_ONE_PRODUCT = 'RECEIVE_ONE_PRODUCT'

export const SET_ITEM_FILTER = 'SET_ITEM_FILTER';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';

export const FETCH_ITEM = 'FETCH_ITEM';
